import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import matter from 'gray-matter';
import { marked } from 'marked';
import { applyAffiliateLinkOverlays, loadAffiliateLinkState } from './lib/affiliate-link-contract.mjs';

const root = process.cwd();
const blogDir = path.join(root, 'src', 'data', 'blog');
const generatedDir = path.join(root, 'src', 'app', 'generated');
const outputPath = path.join(generatedDir, 'content.generated.ts');
const strategyPath = path.join(root, 'src', 'data', 'strategy.json');
const operationsPath = path.join(root, 'src', 'data', 'operations.json');
const growthPath = path.join(root, 'src', 'data', 'growth.json');
const visualsPath = path.join(root, 'visuals', 'article-visuals.json');
const sitemapPath = path.join(root, 'public', 'sitemap.xml');
const affiliateLinkState = await loadAffiliateLinkState(root);
const visualRegistry = JSON.parse(await fs.readFile(visualsPath, 'utf8'));
const visualAssets = new Map(
  visualRegistry.assets.map((asset) => [
    asset.id,
    {
      id: asset.id,
      src: asset.src,
      alt: asset.alt,
      caption: asset.caption,
    },
  ]),
);
const articleVisuals = new Map(visualRegistry.articles.map((entry) => [entry.slug, entry]));

marked.use({ gfm: true, async: false });

const fileNames = (await fs.readdir(blogDir)).filter((name) => name.endsWith('.md')).sort();
const articles = [];
for (const fileName of fileNames) {
  const slug = path.basename(fileName, '.md');
  const parsed = matter(await fs.readFile(path.join(blogDir, fileName), 'utf8'));
  const data = parsed.data;
  const products = data.products ?? [];
  const pairs = data.pairs ?? [];
  const visualEntry = articleVisuals.get(slug);
  if (!visualEntry) throw new Error(`No visual mapping exists for article ${slug}`);
  const hero = visualAssets.get(visualEntry.heroId);
  if (!hero) throw new Error(`Article ${slug} references unknown hero visual ${visualEntry.heroId}`);
  const resolvedPairSceneIds = Object.fromEntries(pairs.map((pair) => [pair.id, visualEntry.pairSceneIds?.[pair.id] ?? visualEntry.heroId]));
  const resolvedProductSceneIds = Object.fromEntries(products.map((product) => {
    const pair = pairs.find((candidate) => candidate.anchorProductId === product.id || candidate.companionProductId === product.id);
    return [product.id, (pair && resolvedPairSceneIds[pair.id]) || visualEntry.heroId];
  }));
  const sceneIds = [...new Set([visualEntry.heroId, ...Object.values(resolvedPairSceneIds), ...Object.values(resolvedProductSceneIds)])];
  const scenes = sceneIds.map((id) => {
    const asset = visualAssets.get(id);
    if (!asset) throw new Error(`Article ${slug} resolves to unknown visual ${id}`);
    return asset;
  });
  const article = {
    slug,
    title: data.title,
    description: data.description,
    publishDate: new Date(data.publishDate).toISOString(),
    updatedDate: new Date(data.updatedDate ?? data.publishDate).toISOString(),
    status: data.status,
    audience: data.audience,
    occasion: data.occasion,
    priceBand: data.priceBand,
    tags: data.tags ?? [],
    researchRun: data.researchRun,
    evidenceScore: Number(data.evidenceScore),
    evidenceMode: data.evidenceMode,
    featured: Boolean(data.featured),
    affiliateDisclosure: Boolean(data.affiliateDisclosure),
    products,
    pairs,
    visual: {
      styleVersion: visualRegistry.styleVersion,
      generator: visualRegistry.generator,
      rightsPosture: visualRegistry.rightsPosture,
      hero,
      scenes,
      productSceneIds: resolvedProductSceneIds,
      pairSceneIds: resolvedPairSceneIds
    },
    contentHtml: marked.parse(parsed.content)
  };
  articles.push(applyAffiliateLinkOverlays(article, affiliateLinkState));
}
const publicArticles = articles.filter((article) => article.status === 'publication_ready');

const strategy = JSON.parse(await fs.readFile(strategyPath, 'utf8'));
const operations = JSON.parse(await fs.readFile(operationsPath, 'utf8'));
const growth = JSON.parse(await fs.readFile(growthPath, 'utf8'));
const banner = '// Generated by scripts/generate-content.mjs. Do not edit by hand.\n';
const source = `${banner}import type { Article, Growth, Operations, Strategy } from '../content.types';\n\n` +
  `export const ARTICLES: readonly Article[] = ${JSON.stringify(publicArticles, null, 2)};\n\n` +
  `export const OPERATIONS: Operations = ${JSON.stringify(operations, null, 2)};\n\n` +
  `export const STRATEGY: Strategy = ${JSON.stringify(strategy, null, 2)};\n\n` +
  `export const GROWTH: Growth = ${JSON.stringify(growth, null, 2)};\n`;

await fs.mkdir(generatedDir, { recursive: true });
await fs.writeFile(outputPath, source);
const paths = [
  '/', '/gift-finder', '/gifts', '/blog', '/standards', '/affiliate-disclosure',
  ...publicArticles.map((article) => `/blog/${article.slug}`)
];
const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...paths.map((urlPath) => `  <url><loc>https://tipsforyourgifts.web.app${urlPath}</loc></url>`),
  '</urlset>',
  ''
].join('\n');
await fs.writeFile(sitemapPath, sitemap);
console.log(`Generated ${path.relative(root, outputPath)} with ${publicArticles.length} public article${publicArticles.length === 1 ? '' : 's'}`);
